### ISSUE TITLE
dbt-core 1.4.1 - cannot import name 'CompilationException' from 'dbt.exceptions'

### ISSUE THREAD

**Issue by mattimoller** [sqlfluff/sqlfluff#4382]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I upgraded dbt-core to version 1.4.1, and aftwerwords any sqlfluff command (including sqlfluff version) return the following error: `ImportError: cannot import name 'CompilationException' from 'dbt.exceptions'`

### Expected Behaviour

Sqlfluff to work with dbt-core 1.4.1 the version (1.4.5)

### Observed Behaviour

Any sqlfluff command is throwing an ImportError

### How to reproduce

pip install dbt-snowflake==1.4.1 sqlfluff==1.4.5 sqlfluff-templater-dbt==1.4.1
sqlfluff version

### Dialect

templater = dbt
dialect = snowflake

### Version

1.4.5, but also tested on 1.4.1 and 1.4.2

### Configuration

[sqlfluff]
templater = dbt
sql_file_exts = .sql
exclude_rules = L004, L031, L034, L029
dialect = snowflake
capitalisation_policy = lower

[sqlfluff:indentation]
indented_joins = false
indented_using_on = true
template_blocks_indent = false
indented_on_contents = false

[sqlfluff:rules]
tab_space_size = 4
max_line_length = 200
indent_unit = space
unquoted_identifiers_policy = all

[sqlfluff:rules:L010]
capitalisation_policy = lower

[sqlfluff:rules:L014]
capitalisation_policy = lower

[sqlfluff:rules:L030]
extended_capitalisation_policy = lower

[sqlfluff:rules:L067]
preferred_type_casting_style = shorthand

[sqlfluff:templater]
unwrap_wrapped_queries = true

[sqlfluff:templater:jinja]
apply_dbt_builtins = true

# sqlfluffignore below
target/
# dbt <1.0.0
dbt_modules/
seeds/
# dbt >=1.0.0
dbt_packages/
macros/
models/data_products/base/devices__aggregated.sql
models/clean/pipedrive/base/deals_unnested.sql
models/utils/daily_date_spine.sql
models/utils/monthly_date_spine.sql
models/clean/planhat/base

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by annebelleo** [comment]
This is a duplicate of https://github.com/sqlfluff/sqlfluff/issues/4315 and already addressed in https://github.com/sqlfluff/sqlfluff/pull/4317

**Comment by mattimoller** [comment]
Thanks for letting me know @annebelleo! I searched the issues, but seems like either m search skills or the the GitHub search algorithm needs to improve 🤔

**Comment by mattimoller** [comment]
closing due to duplicate
