### PR TITLE
feat: Add possibility to set dbt project_dir as environment variable

### PR DESCRIPTION
**Pull request by svdimchenko**
### Brief summary of the change made

Add possibility to set dbt project_dir as environment variable
Minor change to allow usage of DBT_PROJECT_DIR environment variable introduced in https://github.com/dbt-labs/dbt-core/pull/6659

I've also added parameter force_raise_compilation_error because when I run sqlfluff in pre-commit and some errors are just skipped, it leads to broken code passed the linting silently.

### CODE REVIEW

**Comment by svdimchenko** [comment]
@WittierDinosaur @nathanthorell hi there! Could you please take a look at this PR with minor dbt templater improvements?

File: plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py [hunk 1]
```diff
@@ -702,6 +713,8 @@ def render_func(in_str):
                 # to happen if we tried to compile ephemeral models in the
                 # wrong order), but more often because a macro tries to query
                 # a table at compile time which doesn't exist.
+                if self.force_raise_compilation_error:
+                    raise SQLTemplaterError(str(err))
```
Comment (alanmcruickshank) [inline plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py:717]: I'm a little confused. What is this doing with respect to this PR? I understand the bits with the `DBT_PROJECT_DIR` but less this bit.

**Review by alanmcruickshank — COMMENTED** [review]
Thanks for your contribution! Half of this looks very sensible, but I'm quite confused about the compilation error config - I don't understand what purpose that serves.

File: plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py (hunk 1 above)
Comment (svdimchenko) [reply plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py]: @alanmcruickshank no problem, I've changed the parameter name to `skip_dbt_compile_errors`

Comment (svdimchenko) [reply plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py]: @alanmcruickshank kind reminder, is there any chance to get this PR included into the nearest release ?

**Review by WittierDinosaur — APPROVED** [review]
LGTM
